language: java

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P qa

jdk:
  - openjdk11

notifications:
  email:
    - i@sunisle.org
